# Generated by Django 2.1.8 on 2020-10-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaFFPPRellena_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantilla_xlsx', models.FileField(max_length=2000, upload_to='C:\\Users\\slope\\OneDrive\\Escritorio\\EY\\EY_ANGULAR-ELECTRON-DJANGO\\PROYECTO_WEB\\BACK\\WS_DJANGO\\media\\APP_AAP\\EXTERNAL_AUDIT\\FFPP')),
            ],
            options={
                'verbose_name': 'PlantillaFFPPRellena',
                'verbose_name_plural': 'PlantillasFFPPRellenas',
            },
        ),
    ]
